service: gcp-api

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: europe-west2
  project: snappy-bucksaw-120015
  credentials: ./gcloud-keyfile.json

frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello:
    handler: hello
    allowUnauthenticated: true
    events:
      - http: path

custom:
    webpack:
      webpackConfig: 'webpack.config.js'
      includeModules: true
