service: api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-bundle
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          cors: true
